// scrape_schools.js
// Run with `node scrape_schools.js` from the frontend folder.
// Node 18+ ships with a global fetch API so no external package is required.

const cheerio = require('cheerio');
const fs = require('fs');

async function scrapeAll() {
  let schools = [];
  for (let page = 1;; page++) {
    const url = page === 1 ? 'https://shsselect.com/schools' : `https://shsselect.com/schools?page=${page}`;
    // console.log('fetching', url);
    const res = await fetch(url);
    const html = await res.text();
    const $ = cheerio.load(html);
    const cards = $('a.block').filter((i,el)=>$(el).attr('href')?.startsWith('/schools/'));
    if (cards.length === 0) break;
    cards.each((i,el)=>{
      const name = $(el).find('h3').text().trim();
      const cat = $(el).find('span:contains("Category")').parent().text().replace('Category:','').trim();
      const location = $(el).find('span:contains("Location")').parent().text().replace('Location:','').trim();
      const region = location.split(',').pop().trim();
      schools.push({name, category:cat, region});
    });
    // detect if there is a "Next ›" link
    const hasNext = !!$('a:contains("Next ")').length;
    if (!hasNext) break;
  }
  // console.log('scraped', schools.length, 'schools');
  // write to file
  const out = [];
  let id = 1;
  schools.forEach(s => {
    out.push(`  {id:${id++}, name:${JSON.stringify(s.name)}, category:"${s.category}", region:${JSON.stringify(s.region)}},`);
  });
  const content = `// autogenerated from shsselect.com/schools
export const ALL_SCHOOLS = [\n${out.join('\n')}\n];\n`;
  fs.writeFileSync('src/data/schools_new.js', content);
  // console.log('wrote src/data/schools_new.js');
}

scrapeAll().catch(e=>console.error(e));
