-- Delete sample schools and insert all real schools (956 total)
DELETE FROM schools;

INSERT INTO schools (id, name, category, region) VALUES
(1,'Ghana National College','B','Central'),
(2,'Achimota Senior High','A','Greater Accra'),
(3,'Accra Senior High','B','Greater Accra'),
(4,'KNUST Senior High','B','Ashanti'),
(5,'Accra Wesley Girls High','C','Greater Accra'),
(6,'Aggrey Mem. A.M.E.Zion Snr. High','B','Central'),
(7,'Labone Senior High','B','Greater Accra'),
(8,'Ashiaman Senior High','C','Greater Accra'),
(9,'Aburi Girls'' Senior High','A','Eastern'),
(10,'Kumasi Senior High/Tech','C','Ashanti'),
(11,'Presby Senior High, Tema','C','Greater Accra'),
(12,'Presby Boys'' Senior High, Legon','A','Greater Accra'),
(13,'Tema Manhean Senior High/Tech','C','Greater Accra'),
(14,'Wesley Girls'' High School, Cape Coast','A','Central'),
(15,'Accra Academy','A','Greater Accra'),
(16,'St. Louis Senior High, Kumasi','A','Ashanti'),
(17,'Adisadel College','A','Central'),
(18,'Opoku Ware School','A','Ashanti'),
(19,'St. John''s Grammar Senior High','B','Greater Accra'),
(20,'Kumasi Tech. Inst.','A','Ashanti'),
(21,'Methodist Girls Senior High, Mamfe','B','Eastern'),
(22,'Keta Senior High/Tech .','B','Volta'),
(23,'Prempeh College','A','Ashanti'),
(24,'Ada Senior High/Tech.','C','Greater Accra'),
(25,'Armed Forces Senior High/Tech, Kumasi','B','Ashanti'),
(26,'Ghana Senior High, Koforidua','A','Eastern'),
(27,'Mfantsipim School','A','Central'),
(28,'Tema Meth. Day Senior High','C','Greater Accra'),
(29,'Adu Gyamfi Senior High','C','Ashanti'),
(30,'Holy Child School, Cape Coast','A','Central'),
(31,'La Presby Senior High','C','Greater Accra'),
(32,'Anglican Senior High, Kumasi','B','Ashanti'),
(33,'Kumasi Academy','B','Ashanti'),
(34,'Forces Senior High/Tech, Burma Camp','B','Greater Accra'),
(35,'Presby Senior High/Tech, Aburi','C','Eastern'),
(36,'Abura Technical Institute','C','Western'),
(37,'Adonten Senior High','B','Eastern'),
(38,'Presby Senior High, Teshie','C','Greater Accra'),
(39,'Ashiaman Technical Institute','C','Greater Accra'),
(40,'Koforidua Senior High/Tech','A','Eastern'),
(41,'Yaa Asantewaa Girls Senior High .','A','Ashanti'),
(42,'Accra Tech. Trg. Centre','A','Greater Accra'),
(43,'Agona Swedru Technical Institute','B','Central'),
(44,'Ebenezer Senior High','C','Greater Accra'),
(45,'Ejisuman Senior High','C','Ashanti'),
(46,'Mawuli School, Ho','A','Volta'),
(47,'Accra STEM Academy','B','Greater Accra'),
(48,'Apam Senior High','B','Central'),
(49,'Obuasi Senior High/Tech','C','Ashanti'),
(50,'Wesley Grammar School','B','Greater Accra'),
(51,'Abiriw Presby Technical Institute','C','Eastern'),
(52,'Abomosu STEM Senior High','A','Eastern'),
(53,'Ghana Stem Technical School','C','Ashanti'),
(54,'Kumasi Wesley Girls High Sch','B','Ashanti'),
(55,'O''Reilly Senior High','C','Greater Accra'),
(56,'Tema Senior High','A','Greater Accra'),
(57,'Accra Girls Senior High .','A','Greater Accra'),
(58,'Amasaman Senior High/Tech','C','Greater Accra'),
(59,'Holy Trinity Senior High','C','Greater Accra'),
(60,'Agogo State College','C','Ashanti'),
(61,'Mfantsiman Girls'' Senior High','A','Central'),
(62,'Presby Senior High, Osu','C','Greater Accra'),
(63,'St. Augustine''s College, Cape Coast','A','Central'),
(64,'Suhum Senior High/Tech','B','Eastern'),
(65,'West Africa Senior High','B','Greater Accra'),
(66,'Adaklu Senior High','C','Volta'),
(67,'Frafraha Comm. Senior High','C','Greater Accra'),
(68,'Ghanata Senior High','B','Greater Accra'),
(69,'Mankessim Senior High/Tech','C','Central'),
(70,'Archbishop Porter Girls Snr.High .','A','Western'),
(71,'Asanteman Senior High','B','Ashanti'),
(72,'Kumasi Girls Senior High,','B','Ashanti'),
(73,'Okuapeman Senior High','A','Eastern'),
(74,'Takoradi Senior High','C','Western'),
(75,'Abetifi Tech. Inst.','B','Eastern'),
(76,'Awutu Bawjiase Comm. Senior High School','C','Central'),
(77,'Barekese Senior High School','C','Ashanti'),
(78,'Cape Coast Tech. Inst.','A','Central'),
(79,'Chemu Senior High/Tech','B','Greater Accra'),
(80,'Christian Methodist Senior High','C','Greater Accra'),
(81,'Kaneshie Senior High/Tech.','C','Greater Accra'),
(82,'Pope John Snr. High & Min. Sem., Koforidua','A','Eastern'),
(83,'Presby Senior High, Suhum','C','Eastern'),
(84,'St. Peter''s Senior High, Nkwatia','A','Eastern'),
(85,'T. I. Ahmadiyya Senior High, Kumasi','A','Ashanti'),
(86,'Abeadze State College','C','Central'),
(87,'Anum Presby Senior High','C','Eastern'),
(88,'Asesewa Senior High/Tech','C','Eastern'),
(89,'Kumasi High School','A','Ashanti'),
(90,'Kwegyir Aggrey Senior High','C','Central'),
(91,'Odorgonno Senior High','B','Greater Accra'),
(92,'Swedru Senior High','B','Central'),
(93,'University Practice Senior High','B','Central'),
(94,'Abrafi Senior High','C','Bono East'),
(95,'Abuakwa State College','B','Eastern'),
(96,'Akuapem Technical Institute','C','Eastern'),
(97,'Dodowa Technical Institute','C','Greater Accra'),
(98,'New Juaben Senior High/Com','B','Eastern'),
(99,'Obiri Yeboah Senior High/Technical','C','Central'),
(100,'Presby Senior High, Mampong Akwapim','C','Eastern');

INSERT INTO schools (id, name, category, region) VALUES
(101,'St. Hubert Sem/Senior High, Kumasi','B','Ashanti'),
(102,'Suhum Technical Institute','B','Eastern'),
(103,'Sunyani Methodist Technical Inst.','C','Bono'),
(104,'Teshie Tech. Instittute','C','Greater Accra'),
(105,'Abakrampa Senior High/Tech','C','Central'),
(106,'Agomeda Technical Institute','C','Greater Accra'),
(107,'Akokoaso Senior High/Tech','C','Eastern'),
(108,'Amaniampong Senior High','C','Ashanti'),
(109,'Atwima Kwanwoma Snr High/Tech','C','Ashanti'),
(110,'Kibi Senior High/Tech','B','Eastern'),
(111,'Kpando Tech. Inst.','A','Volta'),
(112,'Northern School of Business','C','Northern'),
(113,'Ofori Panin Senior High','A','Eastern'),
(114,'St. Martin''s Senior High, Nsawam','B','Eastern'),
(115,'St. Mary''s Senior High, Korle Gonno','A','Greater Accra'),
(116,'Abosamso Technical Institute','C','Ashanti'),
(117,'Adeiso Presby Senior High','C','Eastern'),
(118,'Adventist Girls Senior High, Ntonso','C','Ashanti'),
(119,'Ahantaman Girls'' Senior High','B','Western'),
(120,'J. A. Kufuor Senior High','C','Ashanti'),
(121,'J.A. Kufour Stem Technical School','C','Ashanti'),
(122,'Kwabenya Comm. Senior High','C','Greater Accra'),
(123,'Swedru Sch. Of Business','C','Central'),
(124,'Tamale Technical Institute','C','Northern'),
(125,'Abetifi Presby Senior High','B','Eastern'),
(126,'Abor Senior High','C','Volta'),
(127,'Agric Nzema Senior High, Kumasi','C','Ashanti'),
(128,'Benkum Senior High','B','Eastern'),
(129,'Jukwa Senior High/Tech','C','Central'),
(130,'Kinbu Senior High/Tech','C','Greater Accra'),
(131,'Ngleshie Amanfro Senior High','C','Greater Accra'),
(132,'Odoben Senior High','C','Central'),
(133,'Okomfo Anokye Senior High','B','Ashanti'),
(134,'Presby Girls Senior High School','C','Ashanti'),
(135,'St. Monica''s Senior High, Mampong','B','Ashanti'),
(136,'St. Rose''s Senior High, Akwatia','A','Eastern'),
(137,'Tema Tech. Inst.','A','Greater Accra'),
(138,'Adjen Kotoku Senior High','C','Greater Accra'),
(139,'Agona Technical Institute','B','Ashanti'),
(140,'Akuse Methodist Senior High/Tech','C','Eastern'),
(141,'Anum Presby Technical Institute','B','Eastern'),
(142,'Assin Foso Technical Institute','A','Central'),
(143,'Effiduase Senior High/Tech','C','Ashanti'),
(144,'Koforidua Tech. Inst.','A','Eastern'),
(145,'Kpando Senior High .','B','Volta'),
(146,'Methodist Senior High, Sekondi','C','Western'),
(147,'Osei Tutu Senior High, Akropong','B','Ashanti'),
(148,'Oti Senior High/Tech Sch','C','Oti'),
(149,'Oyoko Methodist Senior High','B','Eastern'),
(150,'Pentecost Senior High,Koforidua','B','Eastern'),
(151,'Presby Senior High/Tech, Larteh','C','Eastern'),
(152,'Prince Of Peace Girls','C','Ashanti'),
(153,'Simms Senior High/Com.','C','Ashanti'),
(154,'St. Fidelis Senior High/Tech','C','Eastern'),
(155,'Tamale Senior High .','A','Northern'),
(156,'Achinakrom Senior High','C','Ashanti'),
(157,'Adugyama Comm. Senior High','C','Ashanti'),
(158,'Afadjato Senior High/Tech.','C','Volta'),
(159,'Afienya Technical Institute','B','Greater Accra'),
(160,'Afua Kobi Ampem Girls'' Senior High','B','Ashanti'),
(161,'Assin Manso Senior High','C','Central'),
(162,'Assin Nsuta Senior High School','C','Central'),
(163,'Assin State College','C','Central'),
(164,'Awudome Senior High .','B','Volta'),
(165,'Battor Senior High','C','Volta'),
(166,'Beposo Senior High','B','Ashanti'),
(167,'Biriwa Technical Institute','A','Central'),
(168,'Bompeh Senior High./Tech','B','Western'),
(169,'Bosomtwe STEM Academy','A','Ashanti'),
(170,'E. P. Senior High','C','Volta'),
(171,'Effutu Senior High/Tech','C','Central'),
(172,'Ejisu Senior High/Tech','B','Ashanti'),
(173,'H''Mount Sinai Senior High School','C','Eastern'),
(174,'J.E.A. Mills Senior High','C','Central'),
(175,'Kalpohin Senior High','B','Northern'),
(176,'Manso-Adubia Senior High','C','Ashanti'),
(177,'Nkawie Senior High/Tech','C','Ashanti'),
(178,'Nungua Senior High','B','Greater Accra'),
(179,'Odupong Comm. Day School','C','Central'),
(180,'Offinso Technical Institute','C','Ashanti'),
(181,'Our Lady of Mount Carmel Girls Senior High','B','Bono East'),
(182,'Somanya Technical Institute','C','Eastern'),
(183,'St. Michael''s Senior High, Ahenkro','B','Ashanti'),
(184,'St. Stephen''s Presby Snr. High/Tech, Asiakwa','C','Eastern'),
(185,'Yendi Senior High','B','Northern'),
(186,'Zebilla Senior High/Tech','B','Upper East'),
(187,'Zion Senior High','C','Volta'),
(188,'Ada Senior High','B','Greater Accra'),
(189,'Adiembra Senior High','B','Western'),
(190,'Akome Senior High/Tech.','C','Volta'),
(191,'Asamankese Senior High','B','Eastern'),
(192,'Asankrangwa Senior High/Tech','C','Western'),
(193,'Buipe Senior High','C','Savannah'),
(194,'Business Senior High, Tamale','C','Northern'),
(195,'Catholic Technical Institute','C','Ashanti'),
(196,'Comboni Tech/Voc Inst.','B','Volta'),
(197,'Diaso Senior High','B','Central'),
(198,'Enyan-Abaasa Technical Institute','B','Central'),
(199,'Ghana Senior High School, Tamale','A','Northern'),
(200,'Ghana Senior High/Tech','A','Western');

INSERT INTO schools (id, name, category, region) VALUES
(201,'Have Tech. Inst.','B','Volta'),
(202,'Holy Child Senior High School','C','Upper West'),
(203,'Islamic Science Senior High, Tamale','C','Northern'),
(204,'Islamic Senior High,Kumasi','B','Ashanti'),
(205,'Juaboso Senior High','B','Western North'),
(206,'Konongo Odumase Senior High .','A','Ashanti'),
(207,'Kwabeng Anglican Senior High/Tech','B','Eastern'),
(208,'OLA Girls Senior High, Ho','A','Volta'),
(209,'S.D.A Senior High, Sunyani','B','Bono'),
(210,'St. James Sem & Senior High, Abesim','A','Bono'),
(211,'St. Paul''s Tech. Inst.','A','Eastern'),
(212,'St. Thomas Senior High/Tech','C','Eastern'),
(213,'Sunyani Senior High','A','Bono'),
(214,'Sunyani Technical Institute','C','Bono'),
(215,'Yeboah Asuamah Senior High','B','Bono East'),
(216,'Achiase Technical Institute','C','Ashanti'),
(217,'Adabokrom Comm. SHS','C','Western North'),
(218,'Adidome Senior High','C','Volta'),
(219,'Agona Fankobaa Senior High','C','Central'),
(220,'Agona Senior High/Tech','B','Ashanti'),
(221,'Akatsi Senior High/Tech','C','Volta'),
(222,'Akwamuman Senior High','B','Eastern'),
(223,'Anfoega Senior High','C','Volta'),
(224,'Anlo Awomefia Senior High','C','Volta'),
(225,'Atebubu Senior High','C','Bono East'),
(226,'Bosomtwe Senior High/Tech','C','Ashanti'),
(227,'Breman Asikuma Technical Institute','C','Central'),
(228,'Chereponi Senior High/Tech.','C','North East'),
(229,'Dr. Hilla Limann Senior High School','C','Upper West'),
(230,'East Legon Applied Technology Institute','A','Greater Accra'),
(231,'Effiduase Technical Institute','C','Eastern'),
(232,'Ho Technical Institute','C','Volta'),
(233,'J.G. Knol Technical Instititute','C','Eastern'),
(234,'Kade Senior High/Tech.','B','Eastern'),
(235,'Kanda Technical Institute','C','Greater Accra'),
(236,'Kofi Adjei Senior High/Tech','C','Ashanti'),
(237,'Koforidua GRATIS Technical Institute','C','Eastern'),
(238,'Krobea Asante Technical & Vocational Inst.','B','Ashanti'),
(239,'Lashibi Comm. Day','C','Greater Accra'),
(240,'Mankessim Technical Institute','C','Central'),
(241,'Mepe St. Kizito Senior High/Tech.','C','Volta'),
(242,'Nifa Senior High','B','Eastern'),
(243,'Notre Dame Girls Senior High School, Sunyani','A','Bono'),
(244,'Nsawam Senior High','C','Eastern'),
(245,'Opportunities Industrialization Tech. Inst.','C','Greater Accra'),
(246,'Osei Kyeretwie Senior High','B','Ashanti'),
(247,'Osudoku Senior High/Tech.','C','Greater Accra'),
(248,'Pentecost Senior High, Kumasi','C','Ashanti'),
(249,'S.D.A. Senior High. Akim Sekyere','C','Eastern'),
(250,'Sekondi College','A','Western'),
(251,'Sekondi Takoradi Technical Institute','B','Western'),
(252,'Shama Technical Institute','C','Western'),
(253,'Sogakofe Senior High','B','Volta'),
(254,'Sogakope Technial Institute','C','Volta'),
(255,'St. Augustine Senior High School','C','Bono'),
(256,'St. John''s Integrated Snr. High/Tech','C','Upper East'),
(257,'Takoradi Tech. Inst.','A','Western'),
(258,'Twene Amanfo Senior High/Tech.','B','Bono'),
(259,'Tweneboa Kodua Senior High','B','Ashanti'),
(260,'Vakpo Senior High','B','Volta'),
(261,'Winneba Senior High','B','Central'),
(262,'Agotime Senior High','C','Volta'),
(263,'Anlo Afiadenyigba Senior High','C','Volta'),
(264,'Anlo Senior High','B','Volta'),
(265,'Anlo Tech. Inst.','A','Volta'),
(266,'Apeguso Senior High','C','Eastern'),
(267,'Awutu Winton Senior High','B','Central'),
(268,'Axim Girls Senior High','C','Western'),
(269,'Bankoman Senior High','B','Ashanti'),
(270,'Bonwire Senior High/Tech','C','Ashanti'),
(271,'Bortianor Senior High School','C','Greater Accra'),
(272,'Boso Senior High Technical','C','Eastern'),
(273,'Bosome Senior High/Tech.','C','Ashanti'),
(274,'Dabokpa Voc/Tech. Inst.','A','Northern'),
(275,'E.P.C. Mawuko Girls Senior High','B','Volta'),
(276,'Edinaman Senior High','B','Central'),
(277,'Effiduase Senior High/Com','C','Ashanti'),
(278,'Eguafo-Abrem Senior High','C','Central'),
(279,'Fomena T.I. Ahmadiyya Senior High','B','Ashanti'),
(280,'Gbewa Technical Institute','C','Northern'),
(281,'Gomoa Senior High/Tech','C','Central'),
(282,'Government Technical Institute','B','Greater Accra'),
(283,'Holy Family Senior High','C','Upper West'),
(284,'Huni Valley Senior High','C','Western'),
(285,'Kibi Technical Institute','A','Eastern'),
(286,'Kikam Tech. Inst.','A','Western'),
(287,'Kintampo Senior High','C','Bono East'),
(288,'Klo-Agogo Senior High/Tech','C','Eastern'),
(289,'Kokoben Technical Institute','C','Ashanti'),
(290,'Komenda Senior High/Tech.','C','Central'),
(291,'Krobo Girls'' Presby Senior High','A','Eastern'),
(292,'Mafi-Kumasi Senior High/Tech','B','Volta'),
(293,'Mansoman Senior High','C','Ashanti'),
(294,'Methodist High School,Saltpond','B','Central'),
(295,'Moree Comm. Senior High','C','Central'),
(296,'Mpohor Senior High','B','Western'),
(297,'Nima Technical Institute','C','Greater Accra'),
(298,'Obrachire Senior High/Tech','C','Central'),
(299,'Ofoase Kokoben Senior High','B','Ashanti'),
(300,'Oguaa Senior High/Tech','C','Central');

INSERT INTO schools (id, name, category, region) VALUES
(301,'Opoku Agyeman Senior High/Tech','C','Ashanti'),
(302,'Osino Presby Senior High/Tech.','C','Eastern'),
(303,'Owerriman Senior High/Tech','C','Ashanti'),
(304,'Prampram Technical Institute','C','Greater Accra'),
(305,'Presby Senior High, Tamale','C','Northern'),
(306,'Presby Senior High/Tech, Adukrom','C','Eastern'),
(307,'Sacred Heart Tech. Inst.','B','Greater Accra'),
(308,'Salaga T.I. Ahmad Senior High','C','Savannah'),
(309,'Sekondi Technical Institute','C','Western'),
(310,'Senya Senior High School','C','Central'),
(311,'St. Anthony of Padua Senior High/Tech','C','Savannah'),
(312,'St. Catherine Girls Senior High School','C','Volta'),
(313,'St. John''s Senior High, Sekondi','A','Western'),
(314,'St. Joseph''s Tech. Inst.','B','Eastern'),
(315,'St. Mary''s Boys'' Senior High, Apowa','B','Western'),
(316,'Tamale Girls Senior High','B','Northern'),
(317,'Tarkwa Senior High','B','Western'),
(318,'Tarkwa Technical Institute','B','Western'),
(319,'Taviefe Senior High','C','Volta'),
(320,'Techiman Technical Institute','C','Bono East'),
(321,'Tepa Senior High','B','Ashanti'),
(322,'Wesley High School, Bekwai','C','Ashanti'),
(323,'Yilo Krobo Senior High/Com','C','Eastern'),
(324,'Zuarungu Senior High','C','Upper East'),
(325,'Achiase Senior High','B','Eastern'),
(326,'Ada Tech. Inst.','A','Greater Accra'),
(327,'Adjena Senior High/Tech.','C','Eastern'),
(328,'Adjoafua Comm. Senior High','C','Western North'),
(329,'Adobewora Comm. Senior High','C','Ashanti'),
(330,'Afife Senior High Tech.','C','Volta'),
(331,'Afigya Senior High/Tech','C','Ashanti'),
(332,'Afigyaman Senior High School','C','Ashanti'),
(333,'Agona Namonwora Comm.Senior High','C','Central'),
(334,'Ajumako-Afranse Technical Institute','C','Central'),
(335,'Akim Asafo Senior High','C','Eastern'),
(336,'Akim Swedru Senior High','B','Eastern'),
(337,'Akramaman Senior High','C','Greater Accra'),
(338,'Akwatia Tech. Inst.','A','Eastern'),
(339,'Alavanyo Senior High/Tech.','C','Volta'),
(340,'Apagya Senior High','C','Ashanti'),
(341,'Applied Technology Institute - Anyinam','C','Eastern'),
(342,'Asuansi Tech. Inst.','A','Central'),
(343,'Asuom Senior High','C','Eastern'),
(344,'Awaso STEM Senior High','A','Western North'),
(345,'Baidoo Bonso Senior High/Tech','C','Western'),
(346,'Bishop Herman College','A','Volta'),
(347,'Boa-Amponsem Senior High','B','Central'),
(348,'Bolga Tech. Inst.','A','Upper East'),
(349,'Bosomtwe Girls STEM Senior High','A','Ashanti'),
(350,'Brakwa Senior High/Tech','C','Central'),
(351,'Buipe Technical Institute','C','Savannah'),
(352,'Church Of Christ Senior High','C','Ashanti'),
(353,'Diaspora Girls'' Senior High','C','Eastern'),
(354,'Dzodze Penyi Senior High','C','Volta'),
(355,'Ekumfi T. I. Ahmadiiyya SHTS','B','Central'),
(356,'Esaase Bontefufuo Snr. High/Tech.','C','Ashanti'),
(357,'Fettehman Senior High','C','Central'),
(358,'Fiaseman Senior High','C','Western'),
(359,'Fijai Senior High','A','Western'),
(360,'GRATIS Technical Institute, Cape Coast','C','Central'),
(361,'Gambaga Girls Senior High','C','North East'),
(362,'Gomoa Adaa Technical Institute','B','Central'),
(363,'Gyamfi Kumanini Senior High/Tech','B','Ahafo'),
(364,'Kete Krachi Senior High/Tech.','C','Oti'),
(365,'Koase Senior High/Tech','C','Bono'),
(366,'Kofi Annan Technical Institute','C','Northern'),
(367,'Kpedze Senior High','C','Volta'),
(368,'Krobo Comm.Senior High','C','Bono East'),
(369,'Kwame Danso Senior High/Tech','C','Bono East'),
(370,'Kwame Nkrumah Senior High','B','Western'),
(371,'Lamashegu Technical Institute','C','Northern'),
(372,'Mancell Girls'' Senior High/Tech.','C','Ashanti'),
(373,'Methodist Senior High/Tech.,Biadan','C','Bono'),
(374,'Mpraeso Senior High','B','Eastern'),
(375,'Ngleshie Amanfro Technical Institute','C','Greater Accra'),
(376,'Nkoranza Tech Inst.','A','Bono East'),
(377,'Nkroful Agric. Senior High/Tech','C','Western'),
(378,'Nsawkaw State Senior High','B','Bono'),
(379,'Nyakrom Senior High Tech','B','Central'),
(380,'Nyankumasi Ahenkro Snr. High','C','Central'),
(381,'Nyohini Community Technical Institute','C','Northern'),
(382,'OLA Girls Senior High, Kenyasi','A','Ahafo'),
(383,'Oda Senior High','B','Eastern'),
(384,'Osei Adutwum Senior High','C','Ashanti'),
(385,'Parkoso Comm. Senior High','C','Ashanti'),
(386,'Peki Senior High/Technical','C','Volta'),
(387,'Potsin T.I. Ahm. Senior High','C','Central'),
(388,'Queens Girls'' Senior High, Sefwi Awhiaso','C','Western North'),
(389,'Sacred Heart Senior High, Nsoatre','B','Bono'),
(390,'Salvation Army Senior High','B','Bono'),
(391,'Salvation Army Senior High, Akim Wenchi','C','Eastern'),
(392,'Sandema Technical Institute','C','Upper East'),
(393,'Shama Senior High','B','Western'),
(394,'St. Ann''s Girls Senior High, Sampa','B','Bono'),
(395,'St. Augustine Senior High/Tech, Saan Charikpong','C','Upper West'),
(396,'St. Daniel Comboni Technical Institute','B','Volta'),
(397,'St. Francis Seminary Senior High, Buoyem','C','Bono East'),
(398,'St. Francis Senior High/Tech','B','Eastern'),
(399,'St. John''s Voc. Tech. Institute','B','Upper West'),
(400,'St. Joseph Sem/Senior High, Mampong','C','Ashanti');

INSERT INTO schools (id, name, category, region) VALUES
(401,'St. Joseph''s Tech. Inst., Saboba','B','Northern'),
(402,'St. Margaret Mary Snr.High/Tech','B','Greater Accra'),
(403,'St. Mary''s Technical Institute, Asamankese','A','Eastern'),
(404,'St. Michael''s Technical Institute','B','Ashanti'),
(405,'St. Thomas Aquinas Senior High, Cantoments','A','Greater Accra'),
(406,'Suame Technical Institute','A','Ashanti'),
(407,'Techiman Senior High','B','Bono East'),
(408,'Three Town Senior High','C','Volta'),
(409,'Tijjaniya Senior High','C','Ashanti'),
(410,'Toase Senior High','B','Ashanti'),
(411,'Tolon Senior High','C','Northern'),
(412,'Vitting Senior High/Tech.','C','Northern'),
(413,'Volta Tech Inst','C','Volta'),
(414,'Wa Tech. Inst.','A','Upper West'),
(415,'Winneba Technical Institute','A','Central'),
(416,'Yagaba Senior High School','C','North East'),
(417,'Zamse Senior High/Tech','C','Upper East'),
(418,'Abeaseman Comm. Day Senior High','C','Bono East'),
(419,'Abetifi Kyemase Technical Institute','A','Eastern'),
(420,'Aburaman Senior High','C','Central'),
(421,'Abutia Senior High/Tchnical','B','Volta'),
(422,'Adako Jachie Technical Institute','A','Ashanti'),
(423,'Adankwaman Senior High','B','Central'),
(424,'Adanwomase Senior High','C','Ashanti'),
(425,'Adrobaa Technical Institute','C','Ahafo'),
(426,'Adventist Senior High, Kumasi','B','Ashanti'),
(427,'Aflao Community SHTS','C','Volta'),
(428,'Afoako Technical Institute','C','Ashanti'),
(429,'Agate Comm. Senior High','B','Volta'),
(430,'Ahafoman Senior High/Tech','B','Ahafo'),
(431,'Akro Senior High/Tech','C','Eastern'),
(432,'Akrofuom Senior High/Tech','B','Ashanti'),
(433,'Akumfi Ameyaw Senior High/Tech.','B','Bono East'),
(434,'Akwesi Awobaa Senior High/Tech','C','Ashanti'),
(435,'Amedzofe Technical Institute','C','Volta'),
(436,'Amoafo Technical Institute','C','Ashanti'),
(437,'Anbariya Senior High Sch.','C','Northern'),
(438,'Anum Apapam Comm. Day','C','Eastern'),
(439,'Apedwa Presby Senior High','C','Eastern'),
(440,'Asakraka Technical Institute','C','Eastern'),
(441,'Atorkor Technical Institute','C','Volta'),
(442,'Ave Senior High','C','Volta'),
(443,'Ave Technical Institute','C','Volta'),
(444,'Awe Senior High/Tech.','C','Upper East'),
(445,'Axim Technical Institute','B','Western'),
(446,'Ayirebi Senior High','C','Eastern'),
(447,'Baglo Ridge Senior High/Tech.','B','Oti'),
(448,'Bandaman Senior High','C','Bono'),
(449,'Bechem Technical Institute','B','Ahafo'),
(450,'Bedeku Technical Institute','C','Greater Accra'),
(451,'Benso Senior High/Tech','C','Western'),
(452,'Bibiani Senior High/Tech.','C','Western North'),
(453,'Bisease Senior High School','C','Central'),
(454,'Bole Senior High','C','Savannah'),
(455,'Bolgatanga Central Technical Institute','C','Upper East'),
(456,'Bolgatanga Senior High','A','Upper East'),
(457,'Bomaa Comm. Senior High','B','Ahafo'),
(458,'Bongo Senior High','C','Upper East'),
(459,'Bosomtwe Oyoko Comm. Senior High','C','Ashanti'),
(460,'Breman Asikuma Senior High','B','Central'),
(461,'Business Secretarial and Technical Institute','C','Ashanti'),
(462,'College of Music Senior High','C','Central'),
(463,'Damongo Technical Institute','C','Savannah'),
(464,'Danfa Technical Institute','C','Greater Accra'),
(465,'Denyaseman Cath.Senior High','C','Ashanti'),
(466,'Diabene Senior High/Tech','C','Western'),
(467,'Don Bosco Voc./Tech. Inst.','B','Bono'),
(468,'Donkorkrom Agric Senior High','C','Eastern'),
(469,'Dzodze Technical Institute','C','Volta'),
(470,'Ejuraman Anglican Senior High','C','Ashanti'),
(471,'Ejuraman Technical Institute','C','Ashanti'),
(472,'Feyiase Senior High School','C','Ashanti'),
(473,'GRATIS Technical Institute, Bolga','C','Upper East'),
(474,'Gomoa Gyaman Senior High','C','Central'),
(475,'Gyaase Community Senior High','C','Central'),
(476,'Hwidiem Senior High','B','Ahafo'),
(477,'Ibadur Rahman Academy','C','Ashanti'),
(478,'Issa Technical Institute','C','Upper West'),
(479,'Jachie Pramso Senior High','B','Ashanti'),
(480,'Jirapa Senior High','C','Upper West'),
(481,'Juaben Senior High','B','Ashanti'),
(482,'Juaso Senior High/Tech','C','Ashanti'),
(483,'Karaga Senior High','C','Northern'),
(484,'Kintampo Technical Institute','C','Bono East'),
(485,'Kofiase Adventist Senior High/Tech.','B','Ashanti'),
(486,'Kongo Senior High','C','Upper East'),
(487,'Kpalwega Technical Institute','C','Upper East'),
(488,'Kpone Comm. Senior High','C','Greater Accra'),
(489,'Kwahu Ridge Senior High','B','Eastern'),
(490,'Kwahu Tafo Senior High','B','Eastern'),
(491,'Maame Krobo Comm. Senior High','C','Eastern'),
(492,'Mampong/Akw Snr. High/Tech for the Deaf','C','Eastern'),
(493,'Mankranso Senior High','C','Ashanti'),
(494,'Mozano Senior High','B','Central'),
(495,'Mpasatia Senior High/Tech','B','Ashanti'),
(496,'Nalerigu Technical Institute','C','North East'),
(497,'Nandom Senior High','A','Upper West'),
(498,'Ndewura Jakpa Senior High/Tech.','C','Savannah'),
(499,'New Nsutam Senior High/Tech','C','Eastern'),
(500,'Northern Star Senior High','C','Upper West');

INSERT INTO schools (id, name, category, region) VALUES
(501,'Nsoatre Technical Institute','B','Bono'),
(502,'Nuriya Islamic Senior High, Tamale','C','Northern'),
(503,'Oti Boateng Senior High','B','Eastern'),
(504,'Otumfuo Osei Tutu II College','B','Ashanti'),
(505,'Our Lady of Mercy Senior High','B','Greater Accra'),
(506,'Our Lady of Providence Senior High','A','Bono'),
(507,'Panfokrom Technical Institute','A','Central'),
(508,'Piina Senior High','C','Upper West'),
(509,'Ramseyer Technical Institute','C','Ashanti'),
(510,'S.D.A Senior High School, Gomoa Jukwa','C','Central'),
(511,'S.D.A. Senior High, Bekwai','B','Ashanti'),
(512,'Sakafia Islamic Senior High','B','Ashanti'),
(513,'Savelugu Senior High','C','Northern'),
(514,'Saviour Senior High, Osiem','B','Eastern'),
(515,'Sefwi-Wiawso Senior High/Tech','B','Western North'),
(516,'Serwaa Kesse Girls Senior High','A','Ahafo'),
(517,'Siddiq Senior High Sch.','B','Central'),
(518,'St. George''s Senior High Tech.','C','Ashanti'),
(519,'St. Michael''s Senior High, Akoase (Nkawkaw)','C','Eastern'),
(520,'T. I. Ahmadiyya Senior High, Wa','B','Upper West'),
(521,'TSC Technical Institute, Bechem','C','Ahafo'),
(522,'TSC Technical Institute, Dormaa Ahenkro','C','Bono'),
(523,'Tema Mission Technical Institute','A','Greater Accra'),
(524,'Tweapease Senior High School','C','Ashanti'),
(525,'Uthmaniya Senior High, Tafo','C','Ashanti'),
(526,'Vakpo Senior High/Tech','C','Volta'),
(527,'Volta Senior High School','C','Volta'),
(528,'Wa Senior High/Tech.','C','Upper West'),
(529,'Wesley Senior High, Konongo .','B','Ashanti'),
(530,'Weta Senior High/Tech.','C','Volta'),
(531,'Acherensua Senior High','B','Ahafo'),
(532,'Aduman Senior High','B','Ashanti'),
(533,'Ahamansu Islamic Senior High School','C','Oti'),
(534,'Akontombra Senior High','B','Western North'),
(535,'Akrodie Technical Institute','C','Ahafo'),
(536,'Akrofufu Technical Institute','C','Eastern'),
(537,'Akyin Senior High School','C','Central'),
(538,'Al-Azariya Islamic Snr. High, Kumasi','B','Ashanti'),
(539,'Annor Adjaye Senior High','C','Western'),
(540,'Anum Asamoah Senior High/Tech','C','Ashanti'),
(541,'Aperade Senior High/Tech.','C','Eastern'),
(542,'Apesua Comm. Senior High','C','Eastern'),
(543,'Asankare Technical Institute','B','Ashanti'),
(544,'Asankrangwa Senior High','C','Western'),
(545,'Asawinso Senior High','B','Western North'),
(546,'Assin Jakai Applied Technology Institute','C','Central'),
(547,'Asuoso Comm. Senior High','C','Ashanti'),
(548,'Atiavi Senior High/Tech','C','Volta'),
(549,'Attafuah Senior High/Tech','B','Eastern'),
(550,'Atweaman Senior High','C','Eastern'),
(551,'Avatime Senior High','C','Volta'),
(552,'Avenorpeme Technical Institute','C','Volta'),
(553,'Aveyime Battor Senior High/Tech.','C','Volta'),
(554,'Bamboi Comm. Senior High','C','Savannah'),
(555,'Bawku Senior High','B','Upper East'),
(556,'Bawku Senior High/Tech.','C','Upper East'),
(557,'Bawku Tech. Inst.','A','Upper East'),
(558,'Baworo Technical Institute','C','Ashanti'),
(559,'Bechem Presby Senior High','B','Ahafo'),
(560,'Bia Senior High/Tech','B','Western North'),
(561,'Bodomase Senior High/Tech','C','Ashanti'),
(562,'Bodwesango Senior High','C','Ashanti'),
(563,'Bolga Girls Senior High','A','Upper East'),
(564,'Bolga Sherigu Comm. Senior High','C','Upper East'),
(565,'Bowiri Comm. Day Senior High/Tech.','C','Oti'),
(566,'Bueman Senior High .','B','Oti'),
(567,'Bunkpurugu Senior High/Tech','C','North East'),
(568,'C.Y.O. Tech/Voc. Inst.','C','Volta'),
(569,'Caring Sisters Technical Institute','C','Volta'),
(570,'Chiraa Senior High','B','Bono'),
(571,'Christ the King Cath., Obuasi','B','Ashanti'),
(572,'Daboase Senior High/Tech','B','Western'),
(573,'Daffiamah Senior High','C','Upper West'),
(574,'Dambai Technical Institute','C','Oti'),
(575,'Derma Comm. Day School','B','Ahafo'),
(576,'Dodi-Papase Senior High/Tech','C','Oti'),
(577,'Dofor Senior High','C','Volta'),
(578,'Dompoase Senior High','B','Ashanti'),
(579,'Donkro- Nkwanta Senior High School','C','Bono East'),
(580,'Dormaa Senior High','B','Bono'),
(581,'Drobo Senior High','B','Bono'),
(582,'Drobonso Senior High School','C','Ashanti'),
(583,'Dunkwa Senior High/Tech','C','Central'),
(584,'Dwamena Akenten Senior High','B','Ashanti'),
(585,'E. P. Agric Senior High/Tech.','C','Northern'),
(586,'E.P. Tech/Voc Inst','C','Volta'),
(587,'Eremon Senior High/Tech.','C','Upper West'),
(588,'Essipun Technical Institute','C','Western'),
(589,'Fodoa Comm. Senior High','C','Eastern'),
(590,'Fr. Dogli Memorial Technical Institute','C','Oti'),
(591,'Fumbisi Senior High','C','Upper East'),
(592,'GRATIS Technical Institute, Tamale','C','Northern'),
(593,'GRATIS Technical Institute, Wa','C','Upper West'),
(594,'Gbekor Senior High School','C','Volta'),
(595,'Ghana Muslim Mission Senior High','B','Ashanti'),
(596,'Goka Senior High/Tech.','B','Bono'),
(597,'Guakro Effah Senior High','B','Bono East'),
(598,'Gyaama Pensan Senior High/Tech','C','Ashanti'),
(599,'Han Senior High','C','Upper West'),
(600,'Islamic Girls Senior High,Suhum','B','Eastern');

INSERT INTO schools (id, name, category, region) VALUES
(601,'Islamic Senior High, Wa','C','Upper West'),
(602,'Jachie Technical Institute','C','Ashanti'),
(603,'Jacobu Senior High/Tech.','B','Ashanti'),
(604,'Jema Senior High','B','Bono East'),
(605,'Juaben Technical Institute','C','Ashanti'),
(606,'Kadjebi-Asato Senior High','C','Oti'),
(607,'Kajaji Technical Institute','C','Bono East'),
(608,'Kaleo Senior High/Tech','C','Upper West'),
(609,'Kasuliyili Senior High','C','Northern'),
(610,'Keta Business College','C','Volta'),
(611,'Klikor Senior High/Tech.','C','Volta'),
(612,'Ko Senior High','C','Upper West'),
(613,'Kpandai Senior High','C','Northern'),
(614,'Kpong Technical Institute','C','Eastern'),
(615,'Kraboa-Coaltar Presby Snr. High/Tech.','C','Eastern'),
(616,'Krachi Senior High','C','Oti'),
(617,'Kumawu Technical Institute','C','Ashanti'),
(618,'Kumbungu Senior High','C','Northern'),
(619,'Kurofa Methodist Senior High Tech','C','Ashanti'),
(620,'Kusanaba Technical Institute','B','Upper East'),
(621,'Kwabre Senior High','B','Bono East'),
(622,'Kwapong Technical Institute','C','Ahafo'),
(623,'Kyem Amponsah Senior High School, Fiapre','C','Bono'),
(624,'Lassie-Tuolu Senior High','B','Upper West'),
(625,'Leklebi Senior High','C','Volta'),
(626,'Mando Senior High/Tech.','C','Central'),
(627,'Mangoase Senior High','C','Eastern'),
(628,'Mansen Senior High','B','Bono'),
(629,'Manso-Amenfi Comm. Day School','C','Western'),
(630,'Manya Krobo Senior High','B','Eastern'),
(631,'Mem-Chemfre Comm. Senior High','C','Eastern'),
(632,'Methodist Technincal Institute','B','Ashanti'),
(633,'Mim Senior High','B','Ahafo'),
(634,'Naa-Momori Technical Institute','C','Upper West'),
(635,'Nafana Senior High','B','Bono'),
(636,'Nakpanduri Senior High','C','North East'),
(637,'Nalerigu Senior High','C','North East'),
(638,'Nana Brentu Senior High/Tech','C','Western North'),
(639,'Navrongo Technical Institute','C','Upper East'),
(640,'New Ebu Technical Institute','C','Central'),
(641,'New Longoro Comm.School (Dega)','C','Bono East'),
(642,'Ningo Senior High','B','Greater Accra'),
(643,'Nkwabeng Technical Institute','C','Bono East'),
(644,'Nkwanta Comm.Senior High/Tech','C','Oti'),
(645,'Nkwanta Senior High','C','Oti'),
(646,'Nuru-Ameen Islamic Senior High, Asewase','B','Ashanti'),
(647,'Nyinahin Cath. Senior High','C','Ashanti'),
(648,'Nyong Technical Institute','C','Northern'),
(649,'O.L.L. Girls Senior High','C','Upper East'),
(650,'Ofoase Senior High/Tech','C','Ashanti'),
(651,'Okadjakrom Senior High/Tech.','B','Oti'),
(652,'Opportunities Industralisation Technical Inst.','C','Western'),
(653,'Paga Senior High','C','Upper East'),
(654,'Prampram Senior High','B','Greater Accra'),
(655,'Presby Senior High, Begoro','B','Eastern'),
(656,'Presby Senior High/Tech, Kwamang','C','Ashanti'),
(657,'Prestea Senior High/Tech','C','Western'),
(658,'Queen of Peace Senior High, Nadowli','B','Upper West'),
(659,'S.D.A. Senior High, Agona','B','Ashanti'),
(660,'Saboba E.P. Senior High','C','Northern'),
(661,'Sabronum Methodist Senior High/Tech','C','Ashanti'),
(662,'Salaga Technical Institute','C','Savannah'),
(663,'Sankore Senior High','B','Ahafo'),
(664,'Sawla Senior High Sch.','C','Savannah'),
(665,'Sefwi Bekwai Senior High','B','Western North'),
(666,'Serwaah Nyarko Girls'' Snr. High','B','Ashanti'),
(667,'Shia Senior HighTechnical','C','Volta'),
(668,'Sirigu Senior High','C','Upper East'),
(669,'Sokode Senior High/Tech','C','Volta'),
(670,'South Labone Girls Technical Institute','C','Greater Accra'),
(671,'St Sebastian Cath. Senior High','C','Ashanti'),
(672,'St. Ann''s Technical Institute','C','Western'),
(673,'St. Dominic''s Senior High/Tech, Pepease','B','Eastern'),
(674,'St. Gregory Catholic Senior High School','C','Central'),
(675,'St. Mary''s Girl''s Senior High, Konongo','B','Ashanti'),
(676,'St. Mary''s Sem.& Senior High School','B','Oti'),
(677,'St. Mary''s Technical Institute,Tamale','C','Northern'),
(678,'St. Paul''s Senior High, Asakraka Kwahu','C','Eastern'),
(679,'St. Paul''s Senior High, Denu','C','Volta'),
(680,'Suntreso Technical Institute','C','Ashanti'),
(681,'T. I. Ahmadiyya Girl''s Senior High','B','Ashanti'),
(682,'TSC Technical Institute - Asankragwa','C','Western'),
(683,'TSC Technical Institute, Bekwai','C','Ashanti'),
(684,'TSC Technical Institute, Goaso','C','Ahafo'),
(685,'TSC Technical Institute, Konongo','C','Ashanti'),
(686,'TSC Technical Institute, Nadowli - Kaleo','C','Upper West'),
(687,'Takpo Senior High Sch.','C','Upper West'),
(688,'Tanyigbe Senior High','C','Volta'),
(689,'Tapaman Senior High/Tech','C','Oti'),
(690,'Terchire Senior High','C','Ahafo'),
(691,'Tetrefu Technical Institute','C','Ashanti'),
(692,'Tibani Technical Institute','C','Upper West'),
(693,'Tsito Senior High/Tech','C','Volta'),
(694,'Tutu Methodist Technical Institute','C','Eastern'),
(695,'Twereku Ampem Senior High School','C','Ahafo'),
(696,'Twifo Hemang Senior High/Tech','B','Central'),
(697,'Uthman Bin Affan Islamic SHS','C','Western'),
(698,'Wa Senior High .','B','Upper West'),
(699,'Wioso SHS','C','Ashanti'),
(700,'Wulensi Senior High','C','Northern');

INSERT INTO schools (id, name, category, region) VALUES
(701,'Yeji Senior High/Tech','B','Bono East'),
(702,'Zabzugu Senior High','C','Northern'),
(703,'Ziavi Senior High/Tech','C','Volta'),
(704,'Academy of Christ the King','B','Central'),
(705,'Akpafu Senior High/Tech.','C','Oti'),
(706,'Akroso Senior High/Tech','C','Eastern'),
(707,'Akumadan Applied Technology Institute','C','Ashanti'),
(708,'Akumadan Senior High','C','Ashanti'),
(709,'Amankwakrom Fisheries Agric. Tech. Inst.','B','Eastern'),
(710,'Amanten Senior High','B','Bono East'),
(711,'Amenfiman Senior High','B','Western'),
(712,'Amuana Praso Senior High','C','Eastern'),
(713,'Anfoeta Technical Institute','C','Volta'),
(714,'Antoa Senior High','C','Ashanti'),
(715,'Asafora Technical Institute','C','Central'),
(716,'Asare Bediako Senior High .','B','Ashanti'),
(717,'Asasetre Technical Institute','C','Western'),
(718,'Assin North Senior High/Tech','C','Central'),
(719,'Asukawkaw Senior High','C','Oti'),
(720,'Avenor Senior High','C','Volta'),
(721,'Avenui-Awudome Technical Institute','C','Volta'),
(722,'Ayanfuri Senior High','C','Central'),
(723,'Azeem-Namoa Senior High/Tech','C','Upper East'),
(724,'Badu Senior High/Tech.','B','Bono'),
(725,'Banka Comm. Senior High','C','Ashanti'),
(726,'Bassa Community Senior High','C','Bono East'),
(727,'Bepoase Shts','C','Ashanti'),
(728,'Bepong Senior High School','C','Eastern'),
(729,'Berekum Presby Senior High','A','Bono'),
(730,'Berekum Senior High','B','Bono'),
(731,'Biakoye Comm. School','C','Oti'),
(732,'Bimbagu Senior High/Tech','C','North East'),
(733,'Bimbilla Senior High','C','Northern'),
(734,'Binduri Comm. Day Senior High','C','Upper East'),
(735,'Birifo Technical Institute','C','Upper West'),
(736,'Birifoh Senior High Sch.','C','Upper West'),
(737,'Boakye Tromo Senior High/Tech','B','Ahafo'),
(738,'Boanim Senior High/ Tech Sch','C','Ashanti'),
(739,'Bodi Senior High','B','Western North'),
(740,'Bole Technical Institute','C','Savannah'),
(741,'Bongo Technical Institute','C','Upper East'),
(742,'Bonso Nkwanta Technical Institute','C','Western North'),
(743,'Bontrase Senior High Tech. Sch','C','Central'),
(744,'Bonzo-Kaku Senior High','C','Western'),
(745,'Botoku Technical Insitute','C','Volta'),
(746,'Busunya Senior High','C','Bono East'),
(747,'Charlotte Dolphyne Technical Institute','B','Western'),
(748,'Chiana Senior High','C','Upper East'),
(749,'Chirano Comm. Day School','C','Western North'),
(750,'Collins Senior High/Commercial, Agogo','B','Ashanti'),
(751,'Dabala Senior High/Tech.','C','Volta'),
(752,'Daboya Comm. Day School','C','Savannah'),
(753,'Dadease Agric Senior High','C','Ashanti'),
(754,'Dadieso Senior High','B','Western North'),
(755,'Dagbon State Senior High/Tech','C','Northern'),
(756,'Damongo Senior High','C','Savannah'),
(757,'Danso Agyei Senior high technical','C','Ahafo'),
(758,'Denkyembour Technical Institute','C','Eastern'),
(759,'Diamono Senior High Sch.','B','Bono'),
(760,'Dormaa Technical Institute','A','Bono'),
(761,'Duadaso No. 1 Senior High/Tech.','C','Bono'),
(762,'Dwease-Praaso Technical Institute','C','Ashanti'),
(763,'Dzolo Senior High','C','Volta'),
(764,'Enyan Denkyira Senior High/Tech','C','Central'),
(765,'Enyan Maim Comm. Day School','C','Central'),
(766,'Esiama Senior High/Tech','B','Western'),
(767,'Fawohoyeden Technical Institute','C','Ahafo'),
(768,'Funsi Senior High School','C','Upper West'),
(769,'Gambigo Comm. Day Senior High','C','Upper East'),
(770,'Garu Comm. Day Senior High','C','Upper East'),
(771,'Gbintiri Senior High/Tech','C','North East'),
(772,'Gowrie Senior High/Tech.','C','Upper East'),
(773,'Guo Technical Insititute','C','Upper West'),
(774,'Gushegu Senior High','C','Northern'),
(775,'Gwiraman Comm.Senior High','C','Western'),
(776,'Gyarko Comm. Day Senior High','C','Bono East'),
(777,'Gyedu Technical Institute','C','Ahafo'),
(778,'Half Assini Senior High','B','Western'),
(779,'Hemang Buoho Technical Institute','C','Ashanti'),
(780,'Hidaayah Islamic Senior High School','C','Bono'),
(781,'Ho -Lokoe Technical Institute','C','Volta'),
(782,'Islamic Mission Technical Institute','C','Ahafo'),
(783,'Istiquaama Snr. High','B','Bono'),
(784,'Jamiat Al-Hidaya Islamic Girls','C','Upper West'),
(785,'Janga Senior High/Tech','C','North East'),
(786,'Jim Bourton Mem Agric. Senior High','C','Volta'),
(787,'Jinijini Senior High','B','Bono'),
(788,'Jubilee Senior High','C','Ashanti'),
(789,'Kaakyi Technical Institute','C','Oti'),
(790,'Kajaji Senior High','B','Bono East'),
(791,'Kanjarga Comm. Senior High','C','Upper East'),
(792,'Kanton Senior High','B','Upper West'),
(793,'Kedzi Technical Institute','C','Volta'),
(794,'Kesse Basahyia Senior High School','C','Bono East'),
(795,'Klefe Technical Institute','C','Volta'),
(796,'Kobina Ansah SHS','C','Central'),
(797,'Konadu Yiadom Catholic Senior High','B','Ashanti'),
(798,'Konkoma Technical Institute','C','Ashanti'),
(799,'Kpasenpke STEM Senior High','A','North East'),
(800,'Kpassa Senior High/Tech','C','Oti');

INSERT INTO schools (id, name, category, region) VALUES
(801,'Kpeve Senior High Tech','C','Volta'),
(802,'Kukuom Agric Senior High','B','Ahafo'),
(803,'Kumbungu Vocational Techncal Institute','C','Northern'),
(804,'Kusanaba Senior High School','C','Upper East'),
(805,'Kwanyarko Senior High','C','Central'),
(806,'Kwaobaah Nyanoa Comm. Senior High','C','Eastern'),
(807,'Kwarteng Ankomah Senior High','C','Bono East'),
(808,'Kyabobo Girls'' School','C','Oti'),
(809,'Kyekyewere Comm. Senior High School','C','Central'),
(810,'Lambussie Comm. Senior High School','C','Upper West'),
(811,'Langbinsi Senior High/Tech','C','North East'),
(812,'Larabanga Senior High','C','Savannah'),
(813,'Lawra Senior High','A','Upper West'),
(814,'Libermann Technical Institute','C','Western'),
(815,'Likpe Senior High','C','Oti'),
(816,'Loagri Technical Institute','C','North East'),
(817,'Loggu Comm. Day School','C','Upper West'),
(818,'Lolobi Technical Institute','C','Oti'),
(819,'Mabang Senior High/Tech','B','Ashanti'),
(820,'Madina Technical Institute','A','Greater Accra'),
(821,'Manso-Amenfi Technical Institute','C','Western'),
(822,'Menji Senior High','B','Bono'),
(823,'Mesu Akompi Technical Institute','C','Western'),
(824,'Mirigu Community Day Senior High','C','Upper East'),
(825,'Mokwaa Senior High School','C','Central'),
(826,'Morso Senior High/Tech','C','Ashanti'),
(827,'Mpaha Comm. Senior High School','C','Savannah'),
(828,'Naab Azantilow Senior High/Tech.','C','Upper East'),
(829,'Nabango Senior High Tech','C','Upper East'),
(830,'Nabango Technical Institute','C','Upper East'),
(831,'Nakori Chansa Technical Institute','C','Upper West'),
(832,'Namalteng Technical Institute','C','Upper East'),
(833,'Namong Senior High/Tech','C','Ashanti'),
(834,'Nana Ampontua Technical Institute','C','Ashanti'),
(835,'Nanton Senior High/Tech','C','Northern'),
(836,'Nasuan Senior High School','C','North East'),
(837,'Navrongo Senior High','A','Upper East'),
(838,'Nchumuruman Comm. Day Senior High','C','Oti'),
(839,'Nerebehi Technical Institute','C','Ashanti'),
(840,'New Abirem/Afosu Senior High','C','Eastern'),
(841,'New Century Technical Institute','A','Greater Accra'),
(842,'New Edubiase Senior High','B','Ashanti'),
(843,'New Kokrompe Comm. Senior High','C','Bono East'),
(844,'Nkawkaw Senior High','B','Eastern'),
(845,'Nkenkansu Community Senior High','C','Ashanti'),
(846,'Nkonya Senior High School','C','Oti'),
(847,'Nkoranman Senior High','B','Bono'),
(848,'Nkoranza Senior High/Tech','B','Bono East'),
(849,'Nkrankwanta Senior High/Tech','B','Bono'),
(850,'Nkwatia Presby Senior High/Com','B','Eastern'),
(851,'Nkyeraa Senior High Sch.','C','Bono'),
(852,'Notre Dame Sem/ Senior High, Navrongo','A','Upper East'),
(853,'Nsaba Presby Senior High','B','Central'),
(854,'Nsawora Edumafa Senior High School','C','Western North'),
(855,'Nsutaman Cath. Senior High','B','Ashanti'),
(856,'Ntruboman Senior High','C','Oti'),
(857,'Odomaseman Senior High','B','Bono'),
(858,'Ogyeedom Comm.Snr High/Tech','C','Central'),
(859,'Onwe Senior High School','C','Ashanti'),
(860,'Oppong Mem. Senior High','B','Ashanti'),
(861,'Osei Bonsu Senior High','B','Bono East'),
(862,'Otaakrom Technical Institute','C','Ashanti'),
(863,'Our Lady of Fatima Technical Institute','B','Bono'),
(864,'Pakyi Applied Technology Institute','C','Ashanti'),
(865,'Peki Senior High','B','Volta'),
(866,'Pilot Technical Institute','A','Greater Accra'),
(867,'Pong-Tamale Senior High','C','Northern'),
(868,'Prang Senior High','B','Bono East'),
(869,'Presby Boys Model Senior High','C','Eastern'),
(870,'Presby SHTS, Nankpanduri','C','North East'),
(871,'Presby Senior High, Bompata','B','Ashanti'),
(872,'Pusiga Comm. Day Senior High Sch.','C','Upper East'),
(873,'S.D.A Senior High, Koforidua','B','Eastern'),
(874,'Sakogu Senior High/Tech','C','North East'),
(875,'Salaga Senior High','C','Savannah'),
(876,'Samuel Otu Presby Senior High.','B','Ahafo'),
(877,'Sandema Senior High','C','Upper East'),
(878,'Sang Comm. Day School','C','Northern'),
(879,'Sankor Senior High School','C','Western'),
(880,'Santa Esther Girls'' Senior High','C','Volta'),
(881,'Savelugu Technical Institute','C','Northern'),
(882,'Sawla Girls Vocational Institute','C','Savannah'),
(883,'Sefwi-Wiawso Senior High','B','Western North'),
(884,'Sekyedumase Senior High/Tech','B','Ashanti'),
(885,'Sekyere Kusi Senior High School','C','Ashanti'),
(886,'Social Welfare Girls'' Technical Institute','C','Central'),
(887,'Social Welfare Technical Institute, Sunyani','C','Bono'),
(888,'Sombo Senior High','C','Upper West'),
(889,'Some Senior High','C','Volta'),
(890,'Spiritan Senior High/Tech','C','Ashanti'),
(891,'St Anne''s Vocational Training Institute','B','Upper West'),
(892,'St Theresa''s Technical Institute','C','Oti'),
(893,'St. Augustine''s Senior High, Bogoso','C','Western'),
(894,'St. Basilides Voc./Tech. Inst.','B','Upper West'),
(895,'St. Bernadettes Tech/Voc. Institute','C','Upper East'),
(896,'St. Charles Senior High, Tamale','A','Northern'),
(897,'St. Clare''s Technical Institute','C','Upper West'),
(898,'St. Francis Girls Senior High, Jirapa','A','Upper West'),
(899,'St. Jerome Senior High, Abofour','B','Ashanti'),
(900,'St. Joseph Senior High, Sefwi Wiawso','B','Western North');

INSERT INTO schools (id, name, category, region) VALUES
(901,'St. Joseph Senior High/Tech, Ahwiren','B','Ashanti'),
(902,'St. Mary''s Voc./Tech. Inst.','C','Eastern'),
(903,'Sumaman Senior High','B','Bono'),
(904,'TSC Technical Institute - Bibiani','C','Western North'),
(905,'TSC Technical Institute - Garu','C','Upper East'),
(906,'TSC Technical Institute - Half Assini','C','Western'),
(907,'TSC Technical Institute -Kassena Nankana','C','Upper East'),
(908,'TSC Technical Institute, Asamankese','C','Eastern'),
(909,'TSC Technical Institute, Assin Edubiase','C','Central'),
(910,'TSC Technical Institute, Awutu Breku','C','Central'),
(911,'TSC Technical Institute, Donkorkrom','C','Eastern'),
(912,'TSC Technical Institute, Drobo','C','Bono'),
(913,'TSC Technical Institute, Mampong','C','Ashanti'),
(914,'TSC Technical Institute, Sekyere Kumawu','C','Ashanti'),
(915,'Takoradi Community Technical Institute','C','Western'),
(916,'Takrowase Comm. Senior High','C','Eastern'),
(917,'Takrowase Technical Institute','C','Eastern'),
(918,'Tatale Technical Institute','C','Northern'),
(919,'Tawheed Senior High.','B','Ashanti'),
(920,'Tempane Senior High','C','Upper East'),
(921,'Toh-Kpalime Technical Institute','C','Volta'),
(922,'Tongo Senior High/Tech','C','Upper East'),
(923,'Tongor Senior High Tech.','B','Volta'),
(924,'Tsiame Senior High','C','Volta'),
(925,'Tsibu Technical Institute','C','Volta'),
(926,'Tumu Senior High/Tech.','C','Upper West'),
(927,'Tuna Senior High/Tech.','C','Savannah'),
(928,'Tuobodom Senior High/Tech','B','Bono East'),
(929,'Twedie Technical Institute','C','Ashanti'),
(930,'Twifo Praso Senior High','B','Central'),
(931,'Ullo Senior High','C','Upper West'),
(932,'Ve Comm. Senior High','C','Volta'),
(933,'Ve- Golokwati Technical Institute','C','Volta'),
(934,'Volo Comm. Senior High','C','Volta'),
(935,'W.B.M. Zion Senior High, Old Tafo','B','Eastern'),
(936,'Walewale Senior High','C','North East'),
(937,'Walewale Technical Institute','C','North East'),
(938,'Wamanafo Senior High/Tech','B','Bono'),
(939,'Wapuli Comm. Senior High','C','Northern'),
(940,'Wenchi Meth. Senior High','B','Bono'),
(941,'Wiafe Akenten Presby Senior High','C','Ashanti'),
(942,'Wiaga Comm. Senior High','C','Upper East'),
(943,'Woe Technical Institute','C','Volta'),
(944,'Worawora Senior High','C','Oti'),
(945,'Wovenu Senior High Technical','C','Volta'),
(946,'Wulugu Senior High','C','North East'),
(947,'Yaa Pokua Technical Institute','C','Ashanti'),
(948,'Yabram Comm. Day School','C','Oti'),
(949,'Yamfo Anglican Senior High School','B','Ahafo'),
(950,'Yamfo Technical Institute','A','Ahafo'),
(951,'Yizesi Senior High School','C','North East'),
(952,'Yunyoo Senior High School','C','North East'),
(953,'Zabzugu Technical Institute','C','Northern'),
(954,'Ziope Senior High Sch.','C','Volta'),
(955,'Zorkor Senior High','C','Upper East'),
(956,'Zugu Dabogni Technical Institute','C','Northern');

